# Generated by Django 4.2.4 on 2023-08-22 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('can_cancel_permission', 'Can cancel product publication'), ('can_change_desc_permission', 'Can change product description'), ('can_change_category_permission', 'Can change product category')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
