# Generated by Django 4.2.4 on 2023-08-22 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('moderator', 'moderator_admin')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
